### ISSUE TITLE
WebVTT is rejected when using header text

### ISSUE THREAD

**Issue by dvoracek-slub** [shaka-project/shaka-packager#1017]
## System info
**Operating System**: any
**Shaka Packager Version**: e1b0c7c4 (current master)

## Issue and steps to reproduce the problem

The spec allows to place a header text after the WEBVTT magic (https://www.w3.org/TR/webvtt1/#file-structure, 3.), which Packager does not recognize and rejects.

**Packager Command**:
```
packager in=text.vtt,stream=text,output=text_processed.vtt
```

**What is the expected result?**
Packager generates a WebVTT file named "text_processed.vtt" without error. (Ideally, I suppose, the header text should be carried over to the generated file.)

**What happens instead?**
Packager aborts with the following message:
```
[0107/200000:INFO:demuxer.cc(89)] Demuxer::Run() on file 'text.vtt'.
[0107/200000:INFO:demuxer.cc(155)] Initialize Demuxer for file 'text.vtt'.
[0107/200000:ERROR:webvtt_parser.cc(231)] Failed to read WEBVTT header - should be WEBVTT but was WEBVTT Header Text
[0107/200000:ERROR:packager_main.cc(554)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file text.vtt
```

## text.vtt

```vtt
WEBVTT Header Text

00:00.000 --> 00:01.000
Cue Text

00:01.000 --> 00:02.000
Cue Text
```

**Comment by Canta** [comment]
Hi there @dvoracek-slub .

I've faced the same issue on a different situation (live streaming), and already sent a pull request with changes that make shaka packager not rejecting the webvtts.
However, I see the whole shaka group of software is dealing with infrastructure changes, and my pull request fails because of building steps configurations (something unrelated to my code). I can't tell when is that going to be fixed. So, if you happen to need a fix for your issue, you may take a look at the PR and apply the changes yourself locally on your side.

Here are the changes: https://github.com/google/shaka-packager/pull/1027/files
And here's the explanation for all of it: https://github.com/google/shaka-packager/issues/685#issuecomment-1029407191

**Comment by dvoracek-slub** [comment]
Thanks @Canta! Currently my workaround is to preprocess the WEBVTT file, but I'll consider using a custom build.
