### ISSUE TITLE
Dynamic GOP support

### ISSUE THREAD

**Issue by sridhard** [shaka-project/shaka-packager#1048]
This is a query regarding shaka-packager:

For better video compression, commercial video encoders have started using per-shot encoding. In per-scene(or per-shot) encoding the video is encoded separately for each scene and the combined together. This gives the best quality video at lower bitrate.

When video is encoded with per-shot encoding, I frames are places at equal intervals within a scene. but if we consider whole video the I frames are not at regular intervals.

Ex: Input video has scene changes at 0 - 10 - 20 - 30 seconds
each scene is encoded separately and then merged.
In output video I frames are at 0 - 4 - 8 - 10 - 14 - 18 - 20 - 24 - 28  seconds (Considering each scene has GOP size of 4 sec)

Is this kind of packaging supported by shaka-packager? I think in DASH specification this is supported. 

I have raised this query to shaka-player also https://github.com/shaka-project/shaka-player/issues/4025

**Comment by joeyparrish** [comment]
Packager doesn't encode video.  It only packages it.  So if the GOP size is variable, that's fine.  It may result in inconsistent segment durations, though.  This should also be fine.

Quoting your example above:
> Ex: Input video has scene changes at 0 - 10 - 20 - 30 seconds
> In output video I frames are at 0 - 4 - 8 - 10 - 14 - 18 - 20 - 24 - 28 seconds (Considering each scene has GOP size of 4 sec)

If you ask packager for 10-second segments, you would get exactly that, since there are I frames at 10 and 20.

If you ask for 4-second segments, you would get either 4, 4, 2, 4, 4, 2, 4, 4 (rounding down) or 4, 4, 6, 4, 6, 4 (rounding up) or 4, 4, 6, 4, 2, 4, 4 (average).  I would have to dig into the source to remember which of these would be the output.  But the important thing is that Shaka Packager will not and can not break a segment except at I-frame boundaries.

Does this answer your question?

**Comment by sridhard** [comment]
yes. Thanks
