### ISSUE TITLE
Can't get new segments in some mpd live streamming servers

### ISSUE THREAD

**Issue by blockchainFull** [shaka-project/shaka-packager#1100]
I'm trying to parse mpd of several DASH live streamming servers to get newly published segments.

You know, there is a tag named "MinimumUpdatePeriod" in the mpd, so it must be upgraded within this time, and usually 1 or 2 segments are newly published during the period. This way, I can get list of segments regularly, they are accumulated one by one.

But in some servers, they go wrong. Even though minimum update period time is expired, no new segments are published. Instead, random number of segments are published per random interval. I can't understand why this happens.

Currently, I'm using the Google shaka player's submodule to parse mpd and catch segment lists, I don't think there is any problem in it. So That's what I'm so confused. I just made simple Javascript module to use shaka, it works really well in case of normal servers as I said, but not for other ones.

The platform is Ubuntu 20.04, I'm using latest version of shaka player.

Thanks for your reading, I hope your opinions.

**Comment by joeyparrish** [comment]
> But in some servers, they go wrong. Even though minimum update period time is expired, no new segments are published. Instead, random number of segments are published per random interval. I can't understand why this happens.

My guess is caching infrastructure could be responsible.  Sometimes an intermediate cache between the origin and the client could cache the MPD, in particular if it's misconfigured or the cache headers are wrong.  Or the client itself could have a response in cache for the same reasons.

This issue doesn't really appear to be related to Shaka Packager (this repo), so I don't think we can do any more for you here.  But I hope you are able to find the cause, caching or otherwise.  Good luck!
