### ISSUE TITLE
Playback not happening in Apple devices when adding ac4 audio track to content

### ISSUE THREAD

**Issue by ashiskumarsahu** [shaka-project/shaka-packager#1126]
## System info
**Operating System**: All iOS
**Shaka Packager Version**: Latest

## Issue and steps to reproduce the problem
1. We have packaged a content having video resolutions 2160,1080,720,480,320 and 240 and audio formats such as EC4JOC, EC3, AC4 and AAC.
2. In both DRM and Non-DRM case we found video is not playing in apple devices
3. Then I tried by removing random tracks, one at a time and re-pack the content. Surprisingly, it started playing in both non-drm and drm versions when I removed the ac-4 audio track from the packaging command.
4. Note that we are trying with cmaf version.

**Packager Command**:
./shakapackager \
in=AAC.mp4,stream=audio,init_segment=output/audio/aac/init.mp4,playlist_name=output/audio/aac/steam.m3u8,segment_template='output/audio/aac/$Number$.m4s',hls_group_id=audio,hls_name='ENGLISH',lang=en,drm_label=AUDIO \
in=AC4.mp4,stream=audio,init_segment=output/audio/ac4/init.mp4,playlist_name=output/audio/ac4/steam.m3u8,segment_template='output/audio/ac4/$Number$.m4s',hls_group_id=audio,hls_name='ENGLISH',drm_label=AUDIO \
in=EC3.mp4,stream=audio,init_segment=output/audio/ec3/init.mp4,playlist_name=output/audio/ec3/steam.m3u8,segment_template='output/audio/ec3/$Number$.m4s',hls_group_id=audio,hls_name='ENGLISH',drm_label=AUDIO \
in=EC3JOG.mp4,stream=audio,init_segment=output/audio/ec3joc/init.mp4,playlist_name=output/audio/ec3joc/steam.m3u8,segment_template='output/audio/ec3joc/$Number$.m4s',hls_group_id=audio,hls_name='ENGLISH',drm_label=AUDIO \
in=240_out.mp4,stream=video,init_segment=output/video/240/init.mp4,playlist_name=output/video/240/stream.m3u8,iframe_playlist_name=output/video/240/iframe.m3u8,segment_template='output/video/240/segment_$Number$.m4s',drm_label=SD \
in=360_out.mp4,stream=video,init_segment=output/video/360/init.mp4,playlist_name=output/video/360/stream.m3u8,iframe_playlist_name=output/video/360/iframe.m3u8,segment_template='output/video/360/segment_$Number$.m4s',drm_label=SD \
in=480_out.mp4,stream=video,init_segment=output/video/480/init.mp4,playlist_name=output/video/480/stream.m3u8,iframe_playlist_name=output/video/480/iframe.m3u8,segment_template='output/video/480/segment_$Number$.m4s',drm_label=SD \
in=720_out.mp4,stream=video,init_segment=output/video/720/init.mp4,playlist_name=output/video/720/stream.m3u8,iframe_playlist_name=output/video/720/iframe.m3u8,segment_template='output/video/720/segment_$Number$.m4s',drm_label=HD \
in=1080_out.mp4,stream=video,init_segment=output/video/1080/init.mp4,playlist_name=output/video/1080/stream.m3u8,iframe_playlist_name=output/video/1080/iframe.m3u8,segment_template='output/video/1080/segment_$Number$.m4s',drm_label=HD \
in=2160_out.mp4,stream=video,init_segment=output/video/2160/init.mp4,playlist_name=output/video/2160/stream.m3u8,iframe_playlist_name=output/video/2160/iframe.m3u8,segment_template='output/video/2160/segment_$Number$.m4s',drm_label=HD \
--segment_duration 10 \
--generate_static_live_mpd \
--mpd_output output/stream.mpd \

What is the expected result?
As shaka claims to support AC4 format in its official [doc](https://github.com/shaka-project/shaka-packager), it should support the playback in iOS devices.

**Comment by joeyparrish** [comment]
It sounds like the issue is playback on iOS, not packaging.  Does the iOS device support AC4 content?

**Comment by ashiskumarsahu** [comment]
Hi @joeyparrish ,
Thanks for your quick response.

Its not playing in any iOS devices. we have tried with Apple TV, mobile Apps and even in web safari. As the content has other globally supported AAC format it should play in all devices.

Atmos is well detected by our AV receivers when we tried playing the same content by repacking without AC4.
Hope this helps in clarify the exact point of issue I am facing.

Could you please help here?

Thank you

**Comment by joeyparrish** [comment]
> Its not playing in any iOS devices. we have tried with Apple TV, mobile Apps and even in web safari. As the content has other globally supported AAC format it should play in all devices.

Ah, so it's not a matter of AC4 support on iOS.  When you package content with both AC4 and AAC, playback fails on iOS.  Instead, the player should fall back to AAC.  Is that correct?

**Comment by ashiskumarsahu** [comment]
Hi @joeyparrish ,
Sorry for late response. Yes you are correct if AC4 fails its should fallback to AAC. I have tried different demo players like bitmovin, shaka, jw, videojs. I am not sure why its hampering video playback and after removing that particular ac4 track it started playing in all ios devices and well detected atmos and DD+ in supported deceives.

Thank You

**Comment by joeyparrish** [comment]
The problem you're having _sounds_ like a player issue, rather than a packager issue.

All web-based players on iOS today are forced to use Apple's native HLS.  We aren't given access to the web APIs needed to implement HLS in JavaScript.  Therefore none of those players are going to be able to do anything seriously different from one another on iOS.

So I _think_ your issue really needs to be reported to Apple.  If you can try playback on iOS using `src=`, and you have the same issue, I think it's more likely an Apple problem.  Here's what that might look like:

```html
<video controls src="https://example.com/path/to/master.m3u8"></video>
```

Does this help?

**Comment by ashiskumarsahu** [comment]
Hi @joeyparrish,
Thanks for the quick reply.

I already tried this and result is same. Anyway I will post the issue to apple.

One thing I am still very confused that why its hampering playback of entire content. If ac4 is not supported it should play other best supported tracks. Correct me if I am wrong.

_I tried manually removing ac4 track from manifest and in that case also it started working._

Can this be a matter of cmaf's m4s container? Actually I am completely stuck in this and need a quick fix. Alternatively I have to discard AC4 from all content, which I don't want to do.

Thank You

**Comment by joeyparrish** [comment]
I completely agree that if AC4 is not supported by the device, **any** player (native or otherwise) should fall back to AAC.  If it's not, we could guess that one of a couple things is happening:

1. The player is somehow broken with regard to AC4, and doesn't fall back properly.  (In retrospect, this seems unlikely for Apple's native HLS.)
2. The player doesn't fall back to AAC because the device **does** support AC4.  In that case, we could guess that the packager has malformed the AC4 content somehow, causing a playback failure after the codec was chosen from the two alternatives.

Can you confirm whether or not the devices support AC4?  Can you test this on one Apple device that **definitely** has AC4 support, and one Apple device that **definitely doesn't** have AC4 support?  A difference between them should be a very good data point.

**Comment by ashiskumarsahu** [comment]
Hi @joeyparrish,
I will check this and update the analysis here.

Thanks You

**Comment by ashiskumarsahu** [comment]
Hi @joeyparrish,
I could not find any apple device that supports ac4. As per the Apple Document, it only supports Dolby Digital & Stereo. Kindly refer to the support link [here](https://support.apple.com/en-in/HT204069).

Could you please suggest something, if you are familiar with any such device?
I am bit confused on your 2nd point "The player doesn't fall back to AAC because the device does support AC4". It is possible in case of a specific player but I have tried with multiple players.

Thank You

**Comment by ashiskumarsahu** [comment]
Hi @joeyparrish ,
Another update is I tried the same hls in android vlc and its playing fine.

Thank You

**Comment by joeyparrish** [comment]
> I completely agree that if AC4 is not supported by the device, **any** player (native or otherwise) should fall back to AAC. If it's not, we could guess that one of a couple things is happening:
> 
> 1. The player is somehow broken with regard to AC4, and doesn't fall back properly.  (In retrospect, this seems unlikely for Apple's native HLS.)
> 2. The player doesn't fall back to AAC because the device **does** support AC4.  In that case, we could guess that the packager has malformed the AC4 content somehow, causing a playback failure after the codec was chosen from the two alternatives.
> 
> Can you confirm whether or not the devices support AC4? Can you test this on one Apple device that **definitely** has AC4 support, and one Apple device that **definitely doesn't** have AC4 support? A difference between them should be a very good data point.

So, since iOS does not support AC4, Apple's native player should fall back to AAC.  (And every other web-based player is forced to use Apple's native player on iOS.)  Since it does not choose AAC, it seems that something is broken in the player.

If there's anything obviously wrong with the HLS playlists, that could be a packager problem.  Otherwise, I suggest you file iOS playback issues against Apple if you can.

**Comment by ashiskumarsahu** [comment]
> 1. ehow broken with regard to AC4, and doesn't fall back properly.  (In retrosp

Hi @joeyparrish ,
Thanks for suggestion. I believe this should not be a issue of player as I have tried with different players. For posting the issue with apple forum, I will do that.

How I can identify whether its a packager problem or apple's one?

Thank You

**Comment by cosmin** [comment]
Please triage this through one of the players to see why it's not properly falling back to another supported codec. If it turns out to be an issue in the packager output please reopen the issue with the precise issue. As it stands it doesn't appear that the packager output is incorrect if this plays on other devices.
