### ISSUE TITLE
Question:  Outputting live HLS to CDN

### ISSUE THREAD

**Issue by BarryBahrami** [shaka-project/shaka-packager#1151]
Hello,

This is merely a question.  I apologize, I can't find where to submit them. 

I am exploring using shaka packager for packing live HLS streams and am reviewing the whole thing now.

It seems fairly self explanatory to input the different bitrates and have shaka packager package it all together, but how do I get that file out to a CDN?  Do I need to setup nginx alongside shaka packager too and pull it?  Does shaka have a built in web server I can point to as an origin?  I am a little lost here and it's not covered in the documentation.

Thank you in advance.

Barry

**Comment by joeyparrish** [comment]
This is the right place for questions!

There's no built-in web server.  Shaka Packager's sole job is to package (mux output streams and write playlists/manifests).  But the output can either be a filesystem path or a URL.  You can output to a web server that accepts PUT requests.

Cloud storage providers will accept these requests if they have the appropriate authentication tokens/headers.  But for a long-running live stream, those tokens/headers will have to be refreshed periodically.  A static command-line for Packager won't suffice.

There are a few options to solve this:

1. Have Packager write to a local authentication proxy that keeps oauth tokens up-to-date and adds the latest auth header before uploading to your cloud storage provider.  I can help you find the right proxy for GCS or S3 if you need.
2. Use Packager as a C++ library instead of a command-line app, and manage the auth tokens yourself.
3. Use [Shaka Streamer](https://github.com/shaka-project/shaka-streamer), a Python front-end that also manages transcoding through ffmpeg and cloud upload through the external tool `gsutil` from the Google Cloud SDK.  The same tools should also work with S3 if set up properly.

We have plans in Shaka Streamer to replace the `gsutil` approach with built-in oauth proxies (turning option 3 into something more like option 1).  But that work will not be completed until next year.

Does this help?

**Comment by BarryBahrami** [comment]
It does, thank you so much. I can't wait to try this. It looks awesome.
