### ISSUE TITLE
Request for new release to include xhe 

### ISSUE THREAD

**Issue by zwstcoy** [shaka-project/shaka-packager#1307]
Hi, I notices ShakaPackager add xhe support https://github.com/shaka-project/shaka-packager/pull/1092 and haven't not been release for 2 year. I wonder you can create a new release with the xhe change include?

**Comment by cosmin** [comment]
The main branch should be stable, it's just getting harder to build due to the dependencies on gyp and Python 2, etc. But if you have the build environment setup you should be able to build from tip of `main` and expect that to work well.

We're getting relatively close to being able to cut a new release based on the new CMake build system but it might only be after the holidays.

**Comment by 3052** [comment]
yeah the current release is really old at this point. I just got this error:

~~~
[1220/152524:ERROR:stream_descriptor.cc(251)] Unknown field in stream descriptor ("segment").
~~~

even though thats a valid alias from the docs:

https://shaka-project.github.io/shaka-packager/html/documentation.html#stream-descriptors

**Comment by cosmin** [comment]
A new release (3.0) is coming soon, we're working through the last few issues for the release. Watch #1312 for updates.

**Comment by 3052** [comment]
its not really appropriate to close this, since it hasn't actually been fixed. you should push a release, THEN close this issue.

**Comment by joeyparrish** [comment]
We generally close issues from the PR that fixes them in `main`, so since this is fixed in `main`, closing this issue is consistent with our usual practice.  You can watch #1312 for updates on the release as we burn down the remaining issues.
