### ISSUE TITLE
Raw media frame input

### ISSUE THREAD

**Issue by murillo128** [shaka-project/shaka-packager#596]
I would like to integrate the shaka packager into my media server but the API provided by the library is not very friendly for my use case.

I could use the internal APIs as I have access to the raw media frames within my media server and could create a MediaSamples to dispatch directly to a MediaHandler instead of using a Demuxer based on a container format.

The problem with using the internal APIs is that they are not exported in the library, and I would like to avoid having to compile my media server against all the shaka third-party dependencies.

I have started working on modifying the Packager class to be able to pass an external MediaHandler object as input and dispatch the media frames from outside, but it requires using non-public header files (the audio/data stream_info.h ones) in the packager.h.

I was wondering if this is an interesting feature for the project and if it has any possibility of being merged if I create a PR.

Also, any kind of feedback would be very welcome.

**Comment by rkuroiwa** [comment]
IIUC, you would like a way to write a MediaHandler that works in place of a demuxer because you already have a media source that can emit MediaSamples (and other necessary things such as StreamInfo, etc.). At the same time building (the entire custom) shaka-packager on all the machines is something that you want to avoid, instead you want to put something like `libshakapackager.a` on them and link your custom MediaHandler to produce a resulting binary. Am I correct?

How are you planning to build the pipeline? Are you going to overload Packager::Run() method that accepts a MediaHandler that replaces the demuxer?

IMHO, I think it is a nice feature to have and is worth a design doc. Do we want to also support "injecting" a MediaHandlers into the pipeline? If we're allowing a replacement of demuxer MediaHandler, why not be able to replace other MediaHandlers, if so how? We should also think about how we prevent "contaminating" the MediaHandler interface (e.g. accidentally depending on third_party/ files, etc.).

Also what is the goal that you want to achieve? I understand that being able to replace a demuxer with a MediaHandler would unblock you but it sounds like a means than a goal.

These are just my initial thoughts, we can discuss more next week :)

**Comment by murillo128** [comment]
>IIUC, you would like a way to write a MediaHandler that works in place of a demuxer because you already have a media source that can emit MediaSamples (and other necessary things such as StreamInfo, etc.). 

Exactly.

> At the same time building (the entire custom) shaka-packager on all the machines is something that you want to avoid, instead you want to put something like libshakapackager.a on them and link your custom MediaHandler to produce a resulting binary. Am I correct?

I tried to link against the .a, but it didn't had all the symbols (seems I would need to link against all the individual .a libraries) so I switched to use the .so, but then only some symbols are exported. Maybe providing a single bundled .a could be an alternative.

> How are you planning to build the pipeline? Are you going to overload Packager::Run() method that accepts a MediaHandler that replaces the demuxer?


I have forked the project and this is the approach I am currently working on:

https://github.com/medooze/shaka-packager/commit/b50ea7c25977e8a57accc535c90aabf2eaa6ba96

Basically is exporting a factory method for creating a raw input object (that extends the MediaHandler object) and allow to pass it in the StreamDescriptor object. In the initialization, if the raw input is found, no demuxer is created, but used the provided input is found. There is not much change to pipelining (and I hope to have not broke compatibility with current usage).



> IMHO, I think it is a nice feature to have and is worth a design doc. Do we want to also support "injecting" a MediaHandlers into the pipeline? If we're allowing a replacement of demuxer MediaHandler, why not be able to replace other MediaHandlers, if so how? We should also think about how we prevent "contaminating" the MediaHandler interface (e.g. accidentally depending on third_party/ files, etc.).

I am currently only interested in audio/video input, but could be done.

> Also what is the goal that you want to achieve? I understand that being able to replace a demuxer with a MediaHandler would unblock you but it sounds like a means than a goal.

I have a webrtc media server for node (https://github.com/medooze/media-server-node) and I already handle all the media stuff internaly (rtp demuxing and packetization/depacketization), so I am able to access the raw encoded frames and stream info. I would like to pass that to shaka packager to provide HLS/DASH out with as little overhead as possible.

**Comment by rkuroiwa** [comment]
> I tried to link against the .a, but it didn't had all the symbols (seems I would need to link against all the individual .a libraries) so I switched to use the .so

Have you tried settings
`GYP_DEFINES="libpackager_type=static_library"` when running gyp?
https://github.com/google/shaka-packager/search?q=libpackager_type&unscoped_q=libpackager_type

I still have to read the patch. Thx for the patience.

**Comment by murillo128** [comment]
> Have you tried settings `GYP_DEFINES="libpackager_type=static_library"` when running gyp?

I tried it without any setting and dynamic setting, but not static. I will check it next week. If that works I could create my own pipeline and would not need the modification of the `Packager` class.

**Comment by murillo128** [comment]
It didn't work, I still have missing symbols:
```
 undefined symbol: _ZN5shaka5media12MediaHandler14OnFlushRequestEm
```
Seems `libmedia_base.a` is not added to the `libpackager.a` :

```
# ar t libpackager.a
libpackager.job_manager.o
libpackager.muxer_factory.o
libpackager.libcrypto_threading.o
libpackager.packager_util.o
libpackager.packager.o
```

I can link against the individual .a but it seems clumsy. Also, I had to guess the defines used for compilation to disable google protobuf RTTI definitions.

**Comment by murillo128** [comment]
I am stuck at this undefined symbols now:

```
objdump -T build/Release/medooze-shaka-packager.node | grep UND  | grep shaka
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media14BaseDescriptor5WriteEPNS0_12BufferWriterE
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media26VPCodecConfigurationRecordD1Ev
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media14BaseDescriptor11ComputeSizeEv
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media28NalUnitToByteStreamConverterC1Ev
0000000000000000      D  *UND*  0000000000000000              _ZTVN5shaka5media23DecoderConfigDescriptorE
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media26VPCodecConfigurationRecord8ParseMP4ERKSt6vectorIhSaIhEE
0000000000000000      D  *UND*  0000000000000000              _ZTVN5shaka5media22AACAudioSpecificConfigE
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media22AACAudioSpecificConfigC1Ev
0000000000000000      D  *UND*  0000000000000000              _ZTVN5shaka5media6Id3TagE
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media6Id3Tag15AddPrivateFrameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_
0000000000000000      D  *UND*  0000000000000000              _ZTVN5shaka5media12ESDescriptorE
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media26WriteAudioSetupInformationENS0_5CodecEPKhmPNS0_12BufferWriterE
0000000000000000      D  *UND*  0000000000000000              _ZTVN5shaka5media29DecoderSpecificInfoDescriptorE
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media22AACAudioSpecificConfigD1Ev
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media22CalculateEC3ChannelMapERKSt6vectorIhSaIhEEPj
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media6Id3Tag13WriteToVectorEPSt6vectorIhSaIhEE
0000000000000000      D  *UND*  0000000000000000              _ZNK5shaka5media26VPCodecConfigurationRecord9WriteWebMEPSt6vectorIhSaIhEE
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media14BaseDescriptor5ParseERKSt6vectorIhSaIhEE
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media26VPCodecConfigurationRecordC1Ev
0000000000000000      D  *UND*  0000000000000000              _ZN5shaka5media22AACAudioSpecificConfig5ParseERKSt6vectorIhSaIhEE
0000000000000000      D  *UND*  0000000000000000              _ZTVN5shaka5media18SLConfigDescriptorE

```

**Comment by rkuroiwa** [comment]
That is a very short list for what's supposed to be a "stand alone library".

I've read the patch. I'm not sure how the patch is going to work because if it takes the raw media input path, it won't add anything to the `JobManager`. Hence `JobManager::RunJobs()` call in `Packager::Run()` isn't going to do anything.

I have given a little more thought on this problem.
Suppose we were able to provide one big archive file (e.g. libpackager.a) or a shared object. There's still a problem because the headers that are supposed to be "external" are also included using relative paths from the root of the repository. See `packager.h` for example, it includes other headers using a relative path from the root. So the user still needs the whole packager checkout to use the API.
I'm not very familiar with what other libraries do for "dev" packages but I don't think they make the devs checkout the whole repo.

What did you link against to get the list of undefined symbols? Just `libpackager.a`?

**Comment by murillo128** [comment]
>  Hence JobManager::RunJobs() call in Packager::Run() isn't going to do anything.

In fact, I don't need any job, as I am doing any audio and video, and pushing the frames externally from an external thread. (it works).

> What did you link against to get the list of undefined symbols? Just libpackager.a?

I have tried to link against all the `.a` generated, but the symbols are local\hidden and I get the undefined symbols issue. I have been able to merge all of them in a single `.a` file and then link against it  works correctly.

**Comment by astinus-1** [comment]
Based on your last comment, it sounds like you've found a workaround that allows you to link the single .a file. Does that suffice for your workflow? Or is there still interest in submitting a change to export a factory method for creating a raw input object (that extends the MediaHandler object) and allow to pass it in the StreamDescriptor object?

**Comment by murillo128** [comment]
The problem is not the code by how the static library is generate. 

I am creating the `.a` by running the `ar` command with a `-M` and a mri file that adds all the required individual libraries so all the symbols are exposed.
