### ISSUE TITLE
Support muxing audio and video into ts container when using HLS

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [shaka-project/shaka-packager#644]
I'm curious about why separating the audio and video to different ts . What is the consideration of this design? (For reducing the demux for playback).  But the popular HLS streams，which ts contains audio and video. Hope you give some explain.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng It is for compatibility with DASH where demuxed stream is preferred.

We do want to support muxing audio / video in the same container. I'll add it as a feature request and add to backlog for now.

**Comment by megapotz** [comment]
It would be nice to add hls output option with one .m3u8 and one .mp4 file.
For example I have a video file available in 1 resolution. Minimal shaka's output consists of 5 files:

master.m3u8
video.m3u8
audio.m3u8
video.mp4
audio.m4a

while 2 files is enough. Also this type of output adds extra delay, because playback starts after 3-consequent step process. Load master, than audio+video.m3u8 in parrallel, then media. It's also twice more GET requests.

Adding this simple feature would be amazing.

**Comment by cosmin** [comment]
Consolidating this to #802 which describes the same issue
