### ISSUE TITLE
Specify segment start number

### ISSUE THREAD

**Issue by wutchzone** [shaka-project/shaka-packager#852]
Hello,
When using packager for live video with `$Number$` in segment template it would be great to specify from which number to start instead of 0. 

Image situation when packager is packing livestream and it crashes (or some maintenance). For failover it would be great if packager would continue with segment number where it ended instead of starting from 0.

Is there a way how to make it possible?

Thanks

**Comment by sr1990** [comment]
Looks like there is a pending PR for initializing start number through packager option: https://github.com/google/shaka-packager/pull/519. For live streams https://github.com/google/shaka-packager/pull/818 is still being reviewed.

**Comment by kqyang** [comment]
@wutchzone As @sr1990 mentioned, the PR (#818) he is working on right now may help. With his change, the segment start number will be generated from the media timestamp. 

We will probably still need something like #519 but a variation of it as TS timestamp is only 33 bits.

**Comment by jakubvojacek** [comment]
Hello

but starting the segment number from media timestamp will not solve @wutchzone problem right? Because after packager restart, there will be the old segments available but packager's MPD will not point to them. Or do you plan to add some startup check to check for old segments and create the MPD with the old segments as well (and some optional media that will be used to fill the gaps)? 

Thank you
Jakub

**Comment by wutchzone** [comment]
@sr1990 Yes it looks like that #818 could solve my problem, but it looks like that is only for DASH (as PR name says). I would like to apply this feature to both playlists (DASH && HLS). I imagine something much simpler than detecting the segment number from TS. 
For example adding it as argument to the input for packager, example: `input=udp://127.0.0.1:10000,stream=0,init_segment=audio0.mp4,segment_template=audio0_$Number$.m4s,start_segment_number=666`, then packager would start with `audio0_666.m4s` and so on.

And as @jakubvojacek mentions it would be cool to detect "old" segments from last run, but I imagine it would be hard to implement.

**Comment by sr1990** [comment]
@jakubvojacek @wutchzone 
` Because after packager restart, there will be the old segments available but packager's MPD will not point to them. Or do you plan to add some startup check to check for old segments and create the MPD with the old segments as well (and some optional media that will be used to fill the gaps)?`
Yes as you mentioned, the PR does not handle this. @kqyang should be able to tell us if this feature can be added.

`For example adding it as argument to the input for packager, example: input=udp://127.0.0.1:10000,stream=0,init_segment=audio0.mp4,segment_template=audio0_$Number$.m4s,start_segment_number=666, then packager would start with audio0_666.m4s and so on.`
Do you want to create a new mpd or a merged one?
In order to merge, I think you can write a script to merge the mpds into a multi-period one and to address the discontinuity in the merged mpd, can can embed a new period in between pointing to ` optional media that will be used to fill the gaps` as @jakubvojacek has mentioned and also take into consideration time shift buffer depth if required. 
@kqyang what do you think?

**Comment by Canta** [comment]
@wutchzone 
In my experience, HLS couldn't care less about the chunk's filename. It checks for the `#EXT-X-MEDIA-SEQUENCE` tag value: If that's not incremental, players will most likely stall. It means that if you set the proper filename after the restart, but don't change the tag value accordingly to the previous run, it will not work either. That's why last year I've worked in this: https://github.com/google/shaka-packager/issues/691

I do manage incremental numbers in file names after restarts BTW. I use `$Time$` instead of `$Number`, like this: `stuff_$Time%013d$.m4s`. That way, the number only goes up. It saves you from the zero, yet not from the gap. Then again, as I use `$Time$`, I also set the HLS media-sequence tag to a predictable time-based number, and so players are happy.

IDK if this is helpful for your use case, but I did solved my HLS restarts this way.

**Comment by wutchzone** [comment]
@sr1990 
Sorry for my late response. I have patched the behavior that I have described to my fork of shaka packager. If you are interested I can share it via PR.

@Canta thank you for your hint. But his solves only HLS and I would like to use this behavior in Dash as well as in HLS.

**Comment by jakubvojacek** [comment]
@sr1990 

> In order to merge, I think you can write a script to merge the mpds into a multi-period one and to address the discontinuity in the merged mpd, can can embed a new period in between pointing to optional media that will be used to fill the gaps as @jakubvojacek has mentioned and also take into consideration time shift buffer depth if required.

I was thinking of how to create such a script however I got quite lost. I believe it would be beneficial if there was a sample in the packager docs, would the shaka team be willing to write such an example? :)

Thank you
Jakub

**Comment by sr1990** [comment]
`I was thinking of how to create such a script however I got quite lost. I believe it would be beneficial if there was a sample in the packager docs, would the shaka team be willing to write such an example? `
Sorry for the late reply. The script was just a suggestion. I think @kqyang or someone else from the shaka team can point you in the right direction. Thanks.

**Comment by denissabramovs** [comment]
Any updates on this?

**Comment by cosmin** [comment]
This should be solved after #879 was merged
